version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: personeldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "8282:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  postgres-data:

networks:
  appnet:
